version: '3.9'

services:

  mariadb:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: consyn
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
